### ISSUE TITLE
Repository visibility set to private by Github Adeo Admins

### ISSUE THREAD

**Issue by slavogiez** [adeo/hestiaa#37]
The visibility of this repository has been prevently set to private in order to avoid misconfiguration...<br><br>If you really wanted this repository to be public and accessible outside of Adeo, please contact the Factory Team on the #factory Slack channel.<br><br>The Adeo Github Admins.

**Comment by Zizaco** [comment]
Thx for leting us know. This repo is intended to be public, so I'm adding it to the whitelist: https://github.com/adeo/org-settings/pull/1
